spring.application.name=Todo-List
server.port=8082

server.servlet.context-path=/api/v1
spring.datasource.url=jdbc:postgresql://localhost:5432/todoList
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#spring.jpa.defer-datasource-initialisation=true
#spring.sql.init.mode=always
#spring.sql.init.data-locations=classpath:data.sql

jwt.secretKey = YXZuaSBzaGFybWEgaXMgaGVyZSwgbWFraW5nIHRoaXMgdG9kb0xpc3QgcHJvamVjdA==
jwt.refreshExpirationMs = 600000